### ISSUE TITLE
License for round_moons_nasa.jpg

### ISSUE THREAD

**Issue by Pandapip1** [pop-os/cosmic-wallpapers#4]
This image seems likely to be copyrighted by either [the planetary society](https://www.planetary.org/) or Pavel Gabzdyl ("Planetary Society member Pavel Gabzdyl created this composite image of all the known round moons of the planets in our Solar System and of the dwarf planet Pluto.").

Can I clarify that this image is used under license, and if so, under which specific license?

**Comment by git-f0x** [comment]
It's noted on the website that reuse of that image is governed by [NASA's image use policy](https://www.nasa.gov/nasa-brand-center/images-and-media/).

**Comment by Pandapip1** [comment]
I totally missed that. Thanks!
